### ISSUE TITLE
Broken install for PyTorch 1.11

### ISSUE THREAD

**Issue by amundra15** [LeviViana/torch_sampling#10]
Hey,

While installing for PyTorch 1.11.0, I get the following error:

```
path/torch_sampling/csrc/cuda/reservoir_sampling.cuh:15:10: fatal error: THC/THCTensor.h: No such file or directory
   15 | #include <THC/THCTensor.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
Looking into the pyTorch source code, it looks like the file has been permanently removed (in the process of migrating from THC to ATen). How would you suggest handling the issue?

**Comment by amughrabi** [comment]
Do you have any quick ideas to handle this?

Unfortunately, the fix in this PR cannot help: https://github.com/LeviViana/torch_sampling/pull/8

**Comment by amughrabi** [comment]
I fixed it by commenting out `#include <THC/THCTensor.h>`

It works on the latest PyTorch.
