### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by mathild7** [LeviViana/torch_sampling#2]
Python 3.6.9
GCC 8.3.0
Ubuntu 18.04
pytorch 1.2.0
Cuda 10.2
CuDNN 7.6.5

` python3 setup.py build_ext --inplace
running build_ext
building 'torch_sampling' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/home
creating build/temp.linux-x86_64-3.6/home/mat
creating build/temp.linux-x86_64-3.6/home/mat/thesis
creating build/temp.linux-x86_64-3.6/home/mat/thesis/torch_sampling
creating build/temp.linux-x86_64-3.6/home/mat/thesis/torch_sampling/csrc
creating build/temp.linux-x86_64-3.6/home/mat/thesis/torch_sampling/csrc/cpu
creating build/temp.linux-x86_64-3.6/home/mat/thesis/torch_sampling/csrc/cuda
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/mat/thesis/torch_sampling/csrc -I/home/mat/.local/lib/python3.6/site-packages/torch/include -I/home/mat/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/mat/.local/lib/python3.6/site-packages/torch/include/TH -I/home/mat/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /home/mat/thesis/torch_sampling/csrc/sampling.cpp -o build/temp.linux-x86_64-3.6/home/mat/thesis/torch_sampling/csrc/sampling.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=torch_sampling -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/mat/thesis/torch_sampling/csrc -I/home/mat/.local/lib/python3.6/site-packages/torch/include -I/home/mat/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/mat/.local/lib/python3.6/site-packages/torch/include/TH -I/home/mat/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp -o build/temp.linux-x86_64-3.6/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=torch_sampling -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp: In function ‘at::Tensor reservoir_sampling_cpu(at::Tensor&, at::Tensor&, int64_t)’:
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp:78:31: error: expected primary-expression before ‘>’ token
     indices_n.data_ptr<int64_t>(),
                               ^
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp:78:33: error: expected primary-expression before ‘)’ token
     indices_n.data_ptr<int64_t>(),
                                 ^
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp:126:21: error: expected primary-expression before ‘float’
       keys.data_ptr<float>(),
                     ^~~~~
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp:127:35: error: expected primary-expression before ‘float’
       weights_contiguous.data_ptr<float>(),
                                   ^~~~~
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp: In function ‘at::Tensor sampling_with_replacement_cpu(at::Tensor&, at::Tensor&, int64_t)’:
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp:174:52: error: expected primary-expression before ‘>’ token
     int64_t *samples_ptr = samples.data_ptr<int64_t>();
                                                    ^
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp:174:54: error: expected primary-expression before ‘)’ token
     int64_t *samples_ptr = samples.data_ptr<int64_t>();
                                                      ^
/home/mat/thesis/torch_sampling/csrc/cpu/reservoir_sampling.cpp:188:35: error: expected primary-expression before ‘float’
     float *cdf_ptr = cdf.data_ptr<float>();
                                   ^~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by LeviViana** [comment]
Hi, I'm not sure where it might come from, but my first guess is from GCC version -> try compiling with gcc 7.

BTW, you can check the gcc version used to compile your torch binaries:

```python
import torch
print(*torch.__config__.show().split("\n"), sep="\n")
```

**Comment by 7starsea** [comment]
Hi LeviViana, 
 I got the CPU version to work, but the CUDA version does not work.
I am not sure where to go. Here are my simple testing: 

  I got CUDA_HOME is None from the code
`from torch.utils.cpp_extension import CUDA_HOME`, 
however, torch.cuda.is_available() return true.

Need some help, please.

**Comment by LeviViana** [comment]
@mathild7 any news ?

**Comment by mathild7** [comment]
> @mathild7 any news ?

I will revisit this today - haven't had time yet. That said I have a pseudo implementation using torch only that I may stick with. I can share it if it seems to work.

**Comment by mathild7** [comment]
Here is my custom torch implementation for npr:

`def torch_choice(max_idx,num_elem,dev,to_replace=False):
    if(to_replace):
        return torch_choice_replace(max_idx,num_elem,dev)
    else:
        return torch_choice_no_replace(max_idx,num_elem,dev)

def torch_choice_replace(max_idx,num_elem,dev):
    rand_idx = torch.randint(max_idx,(num_elem,),device=dev)
    return rand_idx

def torch_choice_no_replace(max_idx,num_elem,dev):
    if(num_elem > max_idx):
        factor = math.ceil(num_elem/max_idx)
        idx = torch.arange(max_idx).repeat(factor)
        perm = torch.randperm(idx.shape[0], device=dev)
        perm = idx[perm]
        perm = perm[:num_elem]
    else:
        perm = torch.randperm(max_idx, device=dev)[:num_elem]
    return perm`

Let me know if this is way off from what it should be. I believe this would be pseudo reservoir sampling.

**Comment by LeviViana** [comment]
Regarding the `randint`, I actually do it in [cpp](https://github.com/LeviViana/torch_sampling/blob/9f6d4222abd22e92732a123be84849e054b7bfa1/csrc/cpu/reservoir_sampling.cpp#L150) as well as in [cuda](https://github.com/LeviViana/torch_sampling/blob/838a09aadc355ea3fad4093af52a075d99fc9342/csrc/cuda/reservoir_sampling.cu#L232).

Regarding the `randperm`, this is the common workaround, as you can see [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/454bd1ddb4efa421d15b13838c59ed12f9e276cb/maskrcnn_benchmark/modeling/balanced_positive_negative_sampler.py#L49-L50). 

The whole point of this repo is doing sampling more efficiently. You'll see in the notebook [Benchmarks](https://github.com/LeviViana/torch_sampling/blob/master/Benchmark.ipynb) some comparisons with numpy, randperm and etc. So it is up to you to decide whether you need performance or not, if you do, then, as far as I know, this repo is the best option.

I'm closing this issue, but feel free to ask me any further questions.
