### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ilbash** [LeviViana/torch_sampling#5]
import torch
print(*torch.__config__.show().split("\n"), sep="\n")

PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.2
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

I've faced problem when:
>> python setup.py build_ext --inplace
running build_ext
building 'torch_sampling' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/torch_sampling
creating build/temp.linux-x86_64-3.7/torch_sampling/csrc
creating build/temp.linux-x86_64-3.7/torch_sampling/csrc/cpu
creating build/temp.linux-x86_64-3.7/torch_sampling/csrc/cuda
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DWITH_CUDA -I/torch_sampling/csrc -I/usr/local/lib/python3.7/site-packages/torch/include -I/usr/local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/site-packages/torch/include/TH -I/usr/local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/python3.7m -c /torch_sampling/csrc/sampling.cpp -o build/temp.linux-x86_64-3.7/torch_sampling/csrc/sampling.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=torch_sampling -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DWITH_CUDA -I/torch_sampling/csrc -I/usr/local/lib/python3.7/site-packages/torch/include -I/usr/local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.7/site-packages/torch/include/TH -I/usr/local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/python3.7m -c /torch_sampling/csrc/cpu/reservoir_sampling.cpp -o build/temp.linux-x86_64-3.7/torch_sampling/csrc/cpu/reservoir_sampling.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=torch_sampling -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/torch_sampling/csrc/cpu/reservoir_sampling.cpp: In function ‘at::Tensor reservoir_sampling_cpu(at::Tensor&, at::Tensor&, int64_t)’:
/torch_sampling/csrc/cpu/reservoir_sampling.cpp:93:31: error: expected primary-expression before ‘>’token
     indices_n.data_ptr<int64_t>(),
                               ^
/torch_sampling/csrc/cpu/reservoir_sampling.cpp:93:33: error: expected primary-expression before ‘)’token
     indices_n.data_ptr<int64_t>(),
                                 ^
/torch_sampling/csrc/cpu/reservoir_sampling.cpp:141:21: error: expected primary-expression before ‘float’
       keys.data_ptr<float>(),
                     ^~~~~
/torch_sampling/csrc/cpu/reservoir_sampling.cpp:142:35: error: expected primary-expression before ‘float’
       weights_contiguous.data_ptr<float>(),
                                   ^~~~~
/torch_sampling/csrc/cpu/reservoir_sampling.cpp: In function ‘at::Tensor sampling_with_replacement_cpu(at::Tensor&, at::Tensor&, int64_t)’:
/torch_sampling/csrc/cpu/reservoir_sampling.cpp:195:52: error: expected primary-expression before ‘>’ token
     int64_t *samples_ptr = samples.data_ptr<int64_t>();
                                                    ^
/torch_sampling/csrc/cpu/reservoir_sampling.cpp:195:54: error: expected primary-expression before ‘)’ token
     int64_t *samples_ptr = samples.data_ptr<int64_t>();
                                                      ^
/torch_sampling/csrc/cpu/reservoir_sampling.cpp:209:35: error: expected primary-expression before ‘float’
     float *cdf_ptr = cdf.data_ptr<float>();
                                   ^~~~~
error: command 'gcc' failed with exit status 1

**Comment by LeviViana** [comment]
Thanks @Ilyabasharov for reporting the issue. What's your torch version ?

**Comment by ilbash** [comment]
> Thanks @Ilyabasharov for reporting the issue. What's your torch version ?

@LeviViana 1.2.0

**Comment by LeviViana** [comment]
It doesn't look like the original code.

The expression: `float *cdf_ptr = cdf.data_ptr();` can't work, and I didn't find it in the original codebase. What I find is this https://github.com/LeviViana/torch_sampling/blob/master/csrc/cpu/reservoir_sampling.cpp#L209.
